// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB51gJpGuTCVEygAp_hINMYk-fr2TSst_c',
    appId: '1:1058175430164:web:6441f9e12f2b98cdfdc101',
    messagingSenderId: '1058175430164',
    projectId: 'jarnama-app',
    authDomain: 'jarnama-app.firebaseapp.com',
    storageBucket: 'jarnama-app.appspot.com',
    measurementId: 'G-MV6Y1SH171',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAikJ0yWaQI2N8fIh4PqAfIQpbHEXbOjZo',
    appId: '1:1058175430164:android:c5cab973e1c64ac2fdc101',
    messagingSenderId: '1058175430164',
    projectId: 'jarnama-app',
    storageBucket: 'jarnama-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6m0RtkYkU_2bkjU8Tg3SoCqucFNc-sww',
    appId: '1:1058175430164:ios:5aca7501b39ac64efdc101',
    messagingSenderId: '1058175430164',
    projectId: 'jarnama-app',
    storageBucket: 'jarnama-app.appspot.com',
    iosClientId: '1058175430164-mvhcqll182ke048kj1b3tf571veegjbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6m0RtkYkU_2bkjU8Tg3SoCqucFNc-sww',
    appId: '1:1058175430164:ios:5aca7501b39ac64efdc101',
    messagingSenderId: '1058175430164',
    projectId: 'jarnama-app',
    storageBucket: 'jarnama-app.appspot.com',
    iosClientId: '1058175430164-mvhcqll182ke048kj1b3tf571veegjbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );
}
